server.port: 8085

spring:
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/online-shop?serverTimezone=UTC
    username: online-shop-admin
    password: online-shop-admin

